language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  matrix:
  - PACKAGE="cowabloga" OCAML_VERSION=4.01
  - PACKAGE="cowabloga" OCAML_VERSION=4.02
  - PACKAGE="cowabloga" OCAML_VERSION=4.03
